/**
 * Server-side PDF rendering of reports.
 *
 * Uses pdf-lib (pure JS, no native deps / headless browser) to lay out a report
 * context as a real, paginated PDF — title, score row, stats and section tables.
 * Returns raw bytes for `application/pdf` download. Mirrors renderReport (HTML)
 * so the same ReportContext drives both formats.
 */

import { PDFDocument, StandardFonts, rgb, type PDFFont } from "pdf-lib";
import type { ReportContext } from "./engine";
import { REPORT_TITLES } from "./engine";

const INK = rgb(0.06, 0.09, 0.16);
const MUTED = rgb(0.39, 0.45, 0.55);
const BRAND = rgb(0.31, 0.27, 0.9);
const LINE = rgb(0.89, 0.91, 0.94);

function band(score: number) {
  if (score >= 75) return { label: "Critical", c: rgb(0.94, 0.27, 0.27) };
  if (score >= 50) return { label: "High", c: rgb(0.98, 0.45, 0.09) };
  if (score >= 25) return { label: "Medium", c: rgb(0.92, 0.7, 0.03) };
  return { label: "Low", c: rgb(0.13, 0.77, 0.37) };
}

export async function renderReportPdf(ctx: ReportContext): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const W = 595.28; // A4 portrait
  const H = 841.89;
  const margin = 56;
  let page = doc.addPage([W, H]);
  let y = H - margin;

  const text = (s: string, x: number, yy: number, opts: { size?: number; f?: PDFFont; color?: typeof INK } = {}) =>
    page.drawText(s, { x, y: yy, size: opts.size ?? 10, font: opts.f ?? font, color: opts.color ?? INK });

  const ensure = (needed: number) => {
    if (y - needed < margin) {
      page = doc.addPage([W, H]);
      y = H - margin;
    }
  };

  // Header
  text("PrivacyOS", margin, y, { size: 14, f: bold, color: BRAND });
  text("Confidential", W - margin - 60, y, { size: 9, color: MUTED });
  y -= 26;
  text(REPORT_TITLES[ctx.type], margin, y, { size: 20, f: bold });
  y -= 16;
  text(
    `Prepared for ${ctx.subjectName}${ctx.organization ? ` · ${ctx.organization}` : ""} · ${new Date(ctx.generatedAt).toLocaleString()}`,
    margin,
    y,
    { size: 9, color: MUTED },
  );
  y -= 12;
  page.drawLine({ start: { x: margin, y }, end: { x: W - margin, y }, thickness: 2, color: BRAND });
  y -= 28;

  // Score row
  const scores: [string, number][] = [
    ["Overall", ctx.scores.overall],
    ["Privacy", ctx.scores.privacy],
    ["Identity", ctx.scores.identity],
    ["Reputation", ctx.scores.reputation],
    ["Executive", ctx.scores.executive],
    ["Business", ctx.scores.business],
  ];
  const colW = (W - margin * 2) / scores.length;
  scores.forEach(([label, value], i) => {
    const x = margin + i * colW;
    const b = band(value);
    text(String(value), x, y, { size: 20, f: bold, color: b.c });
    text(label.toUpperCase(), x, y - 14, { size: 7, color: MUTED });
    text(b.label, x, y - 24, { size: 7, f: bold, color: b.c });
  });
  y -= 48;

  // Stats
  ctx.stats.forEach((s, i) => {
    const x = margin + (i % 4) * ((W - margin * 2) / 4);
    if (i > 0 && i % 4 === 0) y -= 34;
    text(String(s.value), x, y, { size: 14, f: bold });
    text(s.label, x, y - 12, { size: 7, color: MUTED });
  });
  y -= 40;

  // Sections
  for (const sec of ctx.sections) {
    ensure(40);
    text(sec.heading.toUpperCase(), margin, y, { size: 10, f: bold, color: BRAND });
    y -= 6;
    page.drawLine({ start: { x: margin, y }, end: { x: W - margin, y }, thickness: 0.5, color: LINE });
    y -= 16;
    for (const row of sec.rows) {
      ensure(18);
      text(row.label.slice(0, 60), margin, y, { size: 9, color: MUTED });
      text(row.value.slice(0, 60), margin + 240, y, { size: 9, f: bold });
      y -= 16;
    }
    y -= 14;
  }

  ensure(30);
  page.drawLine({ start: { x: margin, y }, end: { x: W - margin, y }, thickness: 0.5, color: LINE });
  y -= 14;
  text(
    "Auto-generated by the PrivacyOS reporting engine. Scores are 0–100 risk (higher = greater risk). Confidential.",
    margin,
    y,
    { size: 7, color: MUTED },
  );

  return doc.save();
}
