import { Card, RiskBadge, SectionTitle, StatCard } from "@/components/ui";
import { demoExposures } from "@/lib/data/demo";
import { timeAgo } from "@/lib/ui";

export default function ReputationPage() {
  const mentions = demoExposures.filter((e) =>
    ["news", "social_media", "forum"].includes(e.source),
  );

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">Reputation Intelligence</h1>
        <p className="mt-1 text-sm text-slate-400">
          Search visibility, news, sentiment and recovery strategy.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Reputation score" value="64" accent="text-risk-high" hint="Higher = more at risk" />
        <StatCard label="Sentiment" value="Negative" accent="text-risk-high" hint="Trailing 30 days" />
        <StatCard label="Search visibility" value="#2" hint="Harmful result rank" />
        <StatCard label="Mentions tracked" value={mentions.length} hint="News, social, forums" />
      </div>

      <Card>
        <SectionTitle title="Harmful & monitored mentions" subtitle="Ranked by reputation impact" />
        <ul className="divide-y divide-border">
          {mentions.map((m) => (
            <li key={m.id} className="flex items-center justify-between gap-4 py-3">
              <div className="min-w-0">
                <p className="truncate font-medium text-white">{m.sourceName}</p>
                <p className="truncate text-sm text-slate-400">{m.snippet}</p>
              </div>
              <div className="flex items-center gap-3">
                <RiskBadge level={m.riskLevel} />
                <span className="text-xs text-slate-500">{timeAgo(m.lastSeenAt)}</span>
              </div>
            </li>
          ))}
        </ul>
      </Card>

      <Card>
        <SectionTitle title="Recovery plan" subtitle="Generated by the Reputation Agent" />
        <ol className="list-decimal space-y-2 pl-5 text-sm text-slate-300">
          <li>Publish 3 authoritative profiles to reclaim page-one search results.</li>
          <li>Issue verified press to dilute the negative article&apos;s ranking.</li>
          <li>Optimize owned properties (LinkedIn, company bio) for the subject&apos;s name.</li>
          <li>Monitor weekly; escalate to Legal Agent if defamation thresholds are met.</li>
        </ol>
      </Card>
    </div>
  );
}
